version: '3.6'

services:
    myproj_redis:
        container_name: myproj_redis
        hostname: redis
        image: redis:latest
        command: redis-server
        ports:
            - "6379:6379"
        expose:
            - "6379"
        restart: always

    myproj_api:
        container_name: my_api
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
        - "5057:5057"
        working_dir: /home/myproj
        volumes:
            - ./:/home/myproj
        links:
            - myproj_redis
        command: uvicorn api:app --host 0.0.0.0 --port 5057 --reload

    myproj_worker:
        container_name: my_worker
        build:
            context: ./
            dockerfile: ./Dockerfile
        working_dir: /home/myproj
        environment:
            - C_FORCE_ROOT=1
        volumes:
            - ./:/home/myproj
        links:
            - myproj_redis
        command: celery -A controllers.task_module worker --loglevel=INFO
